using System.IO;
using UnityEngine;
using Starsoil.Core;

namespace Starsoil.Data
{
    /// <summary>
    /// Loads the generated recipe catalog (GeneratedData/recipes.json, docs/plan/04)
    /// into a world. Replaced the M1 temp recipe table at M3-T10.
    /// </summary>
    public static class TempRecipes
    {
        public static bool LoadInto(World world)
        {
            string path = DataFiles.RepoGeneratedPath("recipes.json");
            if (path == null || !File.Exists(path))
            {
                Debug.LogError("[Catalog] GeneratedData/recipes.json not found; run RecipeGen --generate.");
                return false;
            }
            world.Crafting.LoadRecipes(CatalogRecipes.ParseJson(File.ReadAllText(path)));
            return true;
        }
    }

    /// <summary>Loads the tech tree from data/tech_nodes.csv (M2-T11; regenerated by
    /// tools/scripts/assign_tech.py as content grows).</summary>
    public static class TechTreeData
    {
        public static bool LoadInto(World world)
        {
            string path = DataFiles.RepoDataPath("tech_nodes.csv");
            if (path == null || !File.Exists(path))
            {
                Debug.LogError("[TechTreeData] data/tech_nodes.csv not found; tech tree empty.");
                return false;
            }
            world.Tech.LoadNodes(TechSystem.ParseCsv(File.ReadAllLines(path)));
            return true;
        }
    }

    /// <summary>Item display names from GeneratedData/items.json (zh/en), used by UI panels
    /// alongside data/localization.csv UI-framework keys.</summary>
    public static class ItemCatalog
    {
        private static readonly System.Collections.Generic.Dictionary<string, (string zh, string en)> Names =
            new System.Collections.Generic.Dictionary<string, (string, string)>();

        public static bool TryLoadDefault()
        {
            string path = DataFiles.RepoGeneratedPath("items.json");
            if (path == null || !File.Exists(path))
            {
                return false;
            }
            Names.Clear();
            var root = Newtonsoft.Json.Linq.JObject.Parse(File.ReadAllText(path));
            if (root["items"] is Newtonsoft.Json.Linq.JArray items)
            {
                foreach (var token in items)
                {
                    if (token is Newtonsoft.Json.Linq.JObject item)
                    {
                        string id = item.Value<string>("Id");
                        if (!string.IsNullOrEmpty(id))
                        {
                            Names[id] = (item.Value<string>("Zh") ?? id, item.Value<string>("En") ?? id);
                        }
                    }
                }
            }
            return true;
        }

        public static string NameOf(string itemId)
        {
            if (Names.TryGetValue(itemId, out var name))
            {
                return L10n.Language == "en" ? name.en : name.zh;
            }
            return L10n.Tr("item_" + itemId);
        }
    }
}
